function mt=stftresm(flin,flout,p)
% create matrix to resample STFT in time
%
%  Inputs: flin(m)      input frame lengths (samples)
%          flout(n)     output frame lengths (samples)
%          p            odd order of the filter generating the intermedate signal [5]
%  Output: mt(n,m)      sparse transformation matrix whose rows sum to 1
%
% Conceptually, the routine first converts the input time series to an
% intermediate piecewise linear signal and then averages this over
% the output bin widths to get the output signal. The intermediate signal
% is chosen so that if tout=tin, the output matrix will approximately equal the identity.
% The intermediate signal is generated by a symmetric FIR filter of order p
%
% To check:
% (1) can we make a better pre-filter
persistent p0 a0
if nargin<3
    p=5;
else
    p=p+1-mod(p,2);                             % round p up to the next higher odd number
end
p2=0.5*(p-1);                                   % number of elements in first half of pre-filter excluding central element
m=length(flin);                                 % number of input frames
n=length(flout);                                % number of output frames
flin=flin(:)';                                  % force a row vector
flout=flout(:)';                                % force a row vector
%
% sort out the pre-filter
%
if isempty(p0) || p~=p0
    % If all frames are the same length, and flout=flin, then the output signal is the intermediate signal filtered by [1 6 1]/8.
    % To calculate the intermediate signal, we therefore would like to apply a filter of order p  that, when convolved with  [1 6 1]/8
    % equals an impulse. This is not possible, so we instead seek a least-squares solution and apply a constraint to force unity DC gain.
    % Since the filter is assumed symmetric, we only calculate its first half.
    if p<3
        a=1;                                        % if p=1, the pre-filter is just a delta function
    else
        fm=0.125*sqrt(2)*toeplitz([1; 6; 1; zeros(p2-1,1)],[1 zeros(1,p2)]); % upper half of forward filter matrix of size p2+2,p2+1) (falsely assuming constant-length frames)
        fm(end,end-1:end)=[0.25 0.75];
        b=[zeros(p2+1,1);1];
        k=2-b(2:end);                               % constraint vector = [2; ... 2; 1] (sum of coefficients = 1)
        ahl=[fm'*fm k; k' 0]\[fm'*b; 1];            % calculate first half of filter and the Lagrange multiplier
        a=[ahl(1:end-1);ahl(end-2:-1:1)];           % symmetric FIR pre-filter of order p
    end
    p0=p;
    a0=a;
else
    a=a0;
end
tpr=repmat((1:m)',1,p);                         % pre-filter matrix row index
tp=sparse(tpr,min(max(tpr+repmat(-p2:p2,m,1),1),m),repmat(a',m,1),m,m); % (m,m) filter matrix
% now integrate over each output frame
tin=cumsum(flin)-0.5*(flin-1);          % sample numbers of centre of each input frame
tout=0.5+[0 cumsum(flout)];             % sample numbers of integration boundaries for output frames
[tall,tix,tjx]=v_sort([tin tout]);      % all the times when the integration changes
nall=length(tall);                      % number of time boundaries = length(tall)
rgix=zeros(2,nall);                     % space to store input and output frame indices corresponding to each segment
rgix(1,tjx(1:m))=1;                     % 1 means new input frame-centre is here
rgix(2,tjx(m+1:end))=1;                 % 1 means new output frame-boundary is here
rgix=cumsum(rgix,2);                    % for i=1:nall-1, interval [tall(i),tall(i+1)] involves inputs rgix(1,i) and rgix(1,i)+1 and output rgix(2,i)
nseg=tjx(end)-1;                        % number of segments that contribute to an output frames
tinx=[tall(1) tin max(tall(end),tin(end)+1)];       % add dummy input times onto the ends to ensure the input range always encompasses the output frames
% wtin gives the relative weight of previous input to this segment integral: 0<=wtin<=1
% it is calculated as the time from the centre of the segment to the to the next input frame-centre divided by
% the time from the previous to the next input frame-centres
wtin=(tinx(rgix(1,1:nseg)+2)-0.5*(tall(1:nseg)+tall(2:nseg+1)))./(tinx(rgix(1,1:nseg)+2)-tinx(rgix(1,1:nseg)+1));      % relative weight of previous input to this segment integral: 0<=wtin<=1
wtin(rgix(1,1:nseg)<=0)=0;                                              % segments below the midpoint of the first input frame just use the first frame
wtin(rgix(1,1:nseg)>=m)=1;                                              % segments beyond the midpoint of the last input frame just use the last frame
ofrac=(tall(2:nseg+1)-tall(1:nseg))./flout(rgix(2,1:nseg));             % calculate what fraction this segment is of its output frame
wtlo=wtin.*ofrac;                                                       % contribution of previous input to this frame integral
wthi=(1-wtin).*ofrac;                                                   % contribution of next input to this frame integral
mt=sparse(repmat(rgix(2,1:nseg),1,2),[max(rgix(1,1:nseg),1) min(rgix(1,1:nseg)+1,m)],[wtlo wthi],n,m)*tp;
if ~nargout
    mtmin=full(min(mt(:)));
    mtmax=full(max(mt(:)));
    plot(tin,mt');
    hold on
    plot(repmat(tin,4,1)+[-0.5;-0.5;0.5;0.5]*(flin-1),repmat(mtmin+(mtmax-mtmin)*(-0.1-0.03*[0;1;1;0]),1,m),'-k');
    plot([repmat(tout(1:n)+0.5,2,1);repmat(tout(2:n+1)-0.5,2,1)],repmat(mtmin+(mtmax-mtmin)*(-0.15-0.03*[0;1;1;0]),1,n),'-k');
    hold off
    xlabel('Input Sample');
    ylabel('I/O frames + Weight');
    v_axisenlarge(-1.05);
    v_texthvc(0.02,0.98,sprintf('Pre-filter error = %.1f dB (p=%d)',10*log10(sum(sum((stftresm(flin,flin,p)-eye(m)).^2))/m),p),'LTk');
end
